services:
  db:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: practice
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
